name: HM CI

on:
  push: 
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: gradle clean build 
        
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    needs: build
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
        
  coverage:
    runs-on: ubuntu-latest
    name: coverage
    needs: build
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Run jococo
      run: gradle jacocoTestReport

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
          coverageFile: 'build/reports/jacoco/test/jacocoTestReport.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
