name: CI

on:
  push: 
    branches: [ "main" ]
  pull_request:    
  workflow_dispatch:  

permissions: write-all
 
jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: gradle clean build

      - name: Jacoco Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: jacoco
          path: build
  
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    needs: build
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool' 
        checkstyle_config: config/checkstyle/checkstyle.xml
        
  coverage:
    runs-on: ubuntu-latest
    name: coverage
    needs: build
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v3

    - name: Jacoco Artifact download
      uses: actions/download-artifact@v3
      with:
          name: jacoco
          path: build
          
    - name: Run jococo
      run: gradle jacocoTestReport   
          
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths:          
           build/reports/jacoco/test/jacocoTestReport.xml           
        token: ${{ secrets.GITHUB_TOKEN }}
        debug-mode: true
        title: Code Coverage
        update-comment: true
